---
title: "bam2prof_plot.md"
author: "Anna Maria Calderon"
date: "2025-05-01"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(reshape2)
library(ggpubr)

setwd("/Users/annamariacalderon//Desktop/KROH/data/dna_damage/")
five_prime <- read.table("5p_results.txt", header = TRUE)
three_prime <- read.table("3p_results.txt", header = TRUE)
```

# Modify Data

```{r modify_data, include=FALSE}
#Fix Column Names
colnames(five_prime) <- c("TAG","SAMPLE","A>C", 
                          "A>G","A>T","C>A","C>G",
                          "C>T","G>A","G>C","G>T",
                          "T>A","T>C","T>G")
colnames(three_prime) <- c("TAG","SAMPLE","A>C", 
                          "A>G","A>T","C>A","C>G",
                          "C>T","G>A","G>C","G>T",
                          "T>A","T>C","T>G")
#Add Length Column
three_prime$LENGTH <- rep(1:10, times=6)
five_prime$LENGTH <- rep(1:10, times=6)

#Reformat to Long 
five_prime_m <- melt(five_prime, 
                  id.vars = c("TAG","SAMPLE","LENGTH"), 
                  variable.name = "DEAM", 
                  value.name = "RATE")

three_prime_m <- melt(three_prime, 
                  id.vars = c("TAG","SAMPLE","LENGTH"), 
                  variable.name = "DEAM", 
                  value.name = "RATE")

#Reformat SAMPLE column
three_prime_m$SAMPLE <- as.character(three_prime_m$SAMPLE)
five_prime_m$SAMPLE <- as.character(five_prime_m$SAMPLE)

```

# Plot 

```{r plot, include=FALSE}
#Color Leg
leg <- c("#429e9f","#42709f",
         "#43429f","#72429f",
         "#9f429e","#9f4270")

#Subset 
G_A_3p <- subset(three_prime_m, three_prime_m$DEAM=="G>A")

#plot
G_A_3p_plot <- ggplot(G_A_3p, aes(x=LENGTH, y=RATE, color=SAMPLE)) +
  geom_line() +
  scale_color_manual(values = leg) +
  scale_x_continuous(breaks = seq(1,10, by=1)) + 
   scale_y_continuous(breaks = seq(0.010,0.030, by=0.005),
                     limits = c(0.010,0.030)) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill=NA, color="black"),
        legend.position=c(0.87,0.80),
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank()) +
  ylab("G>A Substitution Rate") +
  xlab("Distance from 3' end (bp)")


#Subset 
C_T_5p <- subset(five_prime_m, five_prime_m$DEAM=="C>T")

#plot
C_T_5p_plot <- ggplot(C_T_5p, aes(x=LENGTH, y=RATE, color=SAMPLE)) +
  geom_line() +
  scale_color_manual(values = leg) +
  scale_x_continuous(breaks = seq(1,10, by=1)) + 
  scale_y_continuous(breaks = seq(0.010,0.030, by=0.005),
                     limits = c(0.010,0.030)) +
  guides(color=guide_legend(override.aes=list(fill=NA))) +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill=NA, color="black"),
        legend.position=c(0.87,0.80),
        legend.background = element_blank(),
        legend.key = element_blank(),
        legend.title = element_blank()) +
  ylab("C>T Substitution Rate") +
  xlab("Distance from 5' end (bp)")
```

# Arrange and Save

```{r plot, include=FALSE}

deam_GA_CT <- ggarrange(G_A_3p_plot,
          C_T_5p_plot,
          nrow=1,
          ncol = 2,
          widths = c(3,3),
          labels = c('A', 'B'))


ggsave(filename = "deam_GA_CT.png",
       plot = deam_GA_CT, 
       path = "/Users/annamariacalderon/Desktop/KROH/figures/",
       width = 8,
       height = 4,
       units = "in",
       dpi = 300)
```
