---
title: "fst"
author: "Anna Maria Calderon"
date: "2025-05-05"
output: html_document
---

# SETUP

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
library(ggh4x)
setwd("/Users/abc6435/Desktop/KROH/data/pop_structure/")
df <- read.delim("chKIWA_fst.window",
                 header = TRUE,
                 sep = '\t')
df <- na.omit(df)
df$midPos <- as.numeric(df$midPos)
```

# Plot

```{r manhattan_plot, echo=FALSE}
df$chr <- factor(df$chr, levels = unique(df$chr))


fst <- ggplot(df, aes(x = midPos, y = fst, color=chr)) +
  geom_point(size = 0.3) +
  scale_color_manual(
    values=rep(c("black","gray"),length.out=30)) +
  facet_grid(. ~ chr, scales = "free_x", 
             space = "free_x", switch="x") +
  scale_y_continuous(
    expand = c(0, 0),
    breaks=seq(0,1.0,by=0.1),limits=c(0.02,1.0)) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.line = element_line(color="black"),
        axis.ticks = element_blank(),
        axis.text.y = element_text(size=5, color="black"),
        axis.title.y = element_text(size=5, color="black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size=5),
        strip.text.x = element_text(angle=90, vjust = 0.5),
        strip.placement = "outside",
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.spacing = unit(0.0, 'points'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(y = "Fst")


ggsave("fst.png", plot=fst, 
      path ="/Users/abc6435/Desktop/KROH/figures/",
       width = 4.5, height = 2, units = "in", dpi = 300)
```
