---
title: "fst"
author: "Anna Maria Calderon"
date: "2025-04-01"
output: html_document
---

# Download Data

```{bash}

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/pop_structure/fst_corrected.txt /Users/abc6435/Desktop/KROH/data/pop_structure
```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyr)
library(dplyr)
library(qqman)
setwd("/Users/abc6435/Desktop/KROH/data/pop_structure")
```

# Import/Modify Data

```{r import_data}
fst <- read.table("fst_corrected.txt", sep = "\t", header = TRUE)
fst$CHR <- sub("chr","", fst$CHROM)
fst$CHR[fst$CHR == "1a"] <- 1.5
fst$CHR[fst$CHR == "4a"] <- 4.5
fst$CHR <- as.numeric(fst$CHR)
colnames(fst) <- c("CHROM","POS","Fst")
fst$CHROM <- sub("chr","",fst$CHROM)

#Subset every nth row
fst_sub <- fst[seq(1,nrow(fst), 1000), ]
```

# Manhattan Plot

```{r manhattan_plot, echo=FALSE}
fst_sub$CHROM <- factor(fst_sub$CHROM, levels = unique(fst_sub$CHROM))

fst_plot <- ggplot(fst_sub, aes(x = POS, y = Fst)) +
  geom_point(size = 1, color="black", alpha=0.3) +
  facet_wrap(~ CHROM, scales = "free_x", 
             nrow = 3, strip.position = "bottom") +
  scale_y_continuous(expand = c(0,0)) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(), 
        strip.background = element_rect(fill="white"),
        panel.background = element_blank(), 
        panel.spacing = unit(1,'points'),
        panel.border = element_rect(fill=NA, color = "black"))

ggsave("fst.png", plot=fst_plot, 
      path ="/Users/abc6435/Desktop/KROH/figures/",
       width = 3, height = 3, units = "in", dpi = 300)
```
