---
title: "gone"
author: "Anna Maria Calderon"
date: "2025-02-18"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(reshape2)
library(knitr)
```

## Download Data

```{bash}
#Download Files to local
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/gone/results/Ne/* /Users/abc6435/Desktop/KROH/data/gone
```

## Import Data

```{r import_data, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/gone")

ne_files <- list.files(pattern="Output_Ne_*")
ne_list <- list()
for (i in 1:length(ne_files)) {
  ne_list[[i]] <- read.table(ne_files[i], header=TRUE)
}

```

## Modify Data

```{r modify_data}
#Subset the frist 120 generations and bind datasets
for (i in 1:length(ne_files)) {
  ne_list[[i]] <- ne_list[[i]][5:100,]
  colnames(ne_list[[i]]) <- c("gen",paste0("r",i))
}
Ne <- do.call(cbind, ne_list)
Ne <- Ne[, !duplicated(colnames(Ne))]

#Calculate 5-95%ile across repititions
quant_1 <- apply(Ne[,-1], 1, quantile, probs=c(0.10))
quant_2 <- apply(Ne[,-1], 1, quantile, probs=c(0.90))
mean <- apply(Ne[,-1], 1, mean)
median <- apply(Ne[,-1], 1, median)
gen <- seq(min(Ne$gen),max(Ne$gen),1)
ne_stats <- as.data.frame(cbind(gen,mean,median,quant_1,quant_2))


#Melt df
Ne_m <- melt(Ne, id.vars = "gen", value.name = "geom_mean_ne", variable.name = "rep")
```

## Plot Ne Estimates

<https://www.tidyverse.org/blog/2024/02/ggplot2-3-5-0-legends/>

```{r plot, echo=FALSE}
gone <- ggplot(ne_stats, aes(x=gen)) + 
  geom_ribbon(aes(ymin = quant_1, ymax = quant_2), 
              fill="#6874ff", alpha=0.5) +
  geom_line(aes(y=mean, color="Mean"), linewidth=1) +
  geom_line(aes(y=median, color="Median"), linewidth=1) +
  geom_line(data = Ne_m, 
              aes(x = gen, y = geom_mean_ne, alpha=rep), 
              color = "#0013fb", linewidth = 0.05) +
  scale_alpha_discrete(range = c(0.4,0.4)) +
  scale_x_continuous(breaks=seq(0, 120, 10),
                     expand=c(0, 0), limits=c(min(Ne$gen), NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_color_manual(values = c("#6874ff","#b20000" )) +
  xlab("Generation") +
  ylab("Geometric Mean Ne") +
  ggtitle("") +
  guides(alpha = "none") +
  theme(panel.background = element_blank(),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.position = "right", 
        legend.box.spacing = unit(1,"pt"),
        axis.text.x = element_text(size=8, color="black"),
        axis.text.y = element_text(size=8, color="black"),
        panel.border = element_rect(color = "black", fill = NA))

ggsave("gone.png", plot=gone, path ="/Users/abc6435/Desktop",
       width = 5, height = 4, units = "in", dpi = 300)

#Plot Median
gone_med <- ggplot(ne_stats, aes(x=gen, y=median)) + 
  geom_line(linewidth=1, color="#b20000") +
  scale_x_continuous(breaks=seq(0, 120, 10),
                     expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  xlab("Generation") +
  ylab("Geometric Mean Ne") +
  ggtitle("") +
  guides(alpha = "none") +
  theme(panel.background = element_blank(),
        legend.title = element_blank(),
        legend.key = element_blank(),
        legend.position = "right", 
        legend.box.spacing = unit(1,"pt"),
        axis.text.x = element_text(size=8, color="black"),
        axis.text.y = element_text(size=8, color="black"),
        panel.border = element_rect(color = "black", fill = NA))

ggsave("gone_med.png", plot=gone_med, path ="/Users/abc6435/Desktop",
       width = 4, height = 4, units = "in", dpi = 300)

```

## Sensitivity Training Old Code

```{r}
#Melt df
Ne_m <- melt(Ne, id.vars = "gen", value.name = "geom_mean_ne", variable.name = "rep")

r1_10 <- subset(Ne_m, rep %in% c("r1", "r2", "r3", "r4", "r5", 
                        "r6", "r7", "r8", "r9", "r10"))
r1_10$sam <- "10K_snps/chr"

r11_20 <- subset(Ne_m, rep %in% c("r11", "r12", "r13", "r14", "r15", 
                        "r16", "r17", "r18", "r19", "r20"))
r11_20$sam <- "50K_snps/chr"

r21_30 <- subset(Ne_m, rep %in% c("r21", "r22", "r23", "r24", "r25", 
                        "r26", "r27", "r28", "r29", "r30"))
r21_30$sam <- "5K_snps/chr"

r31_40 <- subset(Ne_m, rep %in% c("r31", "r32", "r33", "r34", "r35", 
                        "r36", "r37", "r38", "r39", "r40"))
r31_40$sam <- "25K_snps/chr"

r41_50 <- subset(Ne_m, rep %in% c("r41", "r42", "r43", "r44", "r45", 
                        "r46", "r47", "r48", "r49", "r50"))
r41_50$sam <- "7K_snps/macrochr"

r51_59 <- subset(Ne_m, rep %in% c("r51", "r52", "r53", "r54", "r55", 
                        "r56", "r57", "r58", "r59", "r60"))
r51_59$sam <- "2.5K_snps/macrochr"


NE_m <- rbind(r1_10, r11_20, r21_30, r31_40)

NE_m_mac <- rbind(r41_50, r51_59)
```

```{r}
#Macrochromosomes
colors_mac=c("#ace54e","#4eabe5")
ne_2 <- ggplot(NE_m_mac, aes(x=gen, y=geom_mean_ne, color=sam, alpha=rep)) + 
  geom_line() +
  scale_alpha_discrete(range = c(0.4,0.4)) +
  scale_color_manual(values = colors_mac) +
  scale_x_continuous(breaks=seq(0, 120, 10))  +
  xlab("Generation") +
  ylab("Geometric Mean Ne") +
  ggtitle("") +
  guides(alpha = "none") +
  theme(panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        legend.position = "bottom")

ggsave("ne_2.png", plot=ne_2, path ="/Users/annamariacalderon/Desktop",
       width = 6, height = 6, units = "in", dpi = 300)
```
