---
title: "pca"
author: "Anna Maria Calderon"
date: "2025-04-01"
output: html_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggrepel)
```

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/pop_structure/pca_results.eigen* /Users/abc6435/Desktop/KROH/data/pop_structure

```

# Import/Modify Data

```{r import_data, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/pop_structure")
eigenvec <- read.delim("pca_results.eigenvec", header=F, sep = " ")
eigenval <- read.delim("pca_results.eigenval", header=F)

#Add pop
eigenvec[1:7,1] <- "contemporary"
eigenvec[8:13,1] <- "historical"
```

# Percent Variance Explained

```{r per_var_ex, include=FALSE}
percent_var <- (eigenval$V1 / sum(eigenval$V1)) * 100
```

# Plot

```{r}
leg <- c("contemporary" = "gray","historical" = "black")

pca <- ggplot(eigenvec, aes(x = V3, y = V4)) +
  geom_point(shape = 21, size = 3, 
             colour = "black", stroke = 1, aes(fill=V1)) +
  scale_fill_manual(values=alpha(leg, 1.0)) +
  xlab(paste0("PC1: ", round(percent_var[1], 2), "% variance")) +
  ylab(paste0("PC2: ", round(percent_var[2], 2), "% variance")) +
  theme(
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black"),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill=NA), 
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(0,0,0,0),
    legend.box.spacing = unit(0, "pt"))

ggsave("pca.png", plot=pca, 
       path ="/Users/abc6435/Desktop/KROH/figures/",
       width = 3, height = 3, units = "in", dpi = 300)
```
