---
inst---
title: "PCAngsd"
author: "Anna Maria Calderon"
date: "2024-04-19"
output: html_document
---

# Load Packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RcppCNPy)
library(stats)
library(FactoMineR)
library(ade4)
library(ggplot2)
```

# Import Data

```{r import_data}
setwd("/Users/abc6435/Desktop/hWROH/data")
C <- as.matrix(read.table("output.cov"))
```

# Calculate PCA Vectors

<https://github.com/nt246/lcwgs-guide-tutorial/blob/main/tutorial3_ld_popstructure/markdowns/pca_admixture.md#principal-components-analysis-pca>

The highest eigenvalues correspond to the first data principal components.

```{r eigenvalues, echo=FALSE}
#Add Population Assignments
pop <- c("cKIWA", "cKIWA", "cKIWA", "cKIWA", "cKIWA", "cKIWA", "cKIWA",
         "hKIWA", "hKIWA", "hKIWA", "hKIWA", "hKIWA", "hKIWA")

#rows are in same order as input bam.filelist -b 
sample <- c("183194841", "183194861", "183195304", 
            "183195312", "183195321", "183195326","183195332", 
            "29779", "383194", "383202", 
            "383205", "507264", "507265")

cov <- c("3.02006", "2.99842", "2.9577" ,"3.08131" ,"2.88418" ,"2.98133", "3.04897",
         "2.15895", "3.00758", "2.91015", "2.89528", "2.97345", "2.99665")

sample_year <- c("2006", "2006", "2006", 
            "2006", "2006", "2006","2006", 
            "1884", "1914", "1915", 
            "1905", "1902", "1904")




mme.pca <- eigen(C)
eigenvectors = mme.pca$vectors
pca.vectors = as_tibble(cbind(pop, sample, cov, sample_year, data.frame(eigenvectors)))


```

# Compute PCA Variance

```{r pca_var}

pca.eigenval.sum = sum(mme.pca$values) #sum of eigenvalues
varPC1 <- (mme.pca$values[1]/pca.eigenval.sum)*100 #Variance explained by PC1
varPC2 <- (mme.pca$values[2]/pca.eigenval.sum)*100 #Variance explained by PC2
varPC3 <- (mme.pca$values[3]/pca.eigenval.sum)*100 #Variance explained by PC3
varPC4 <- (mme.pca$values[4]/pca.eigenval.sum)*100 #Variance explained by PC4
```

# Plot PCA

```{r plot_pca}
pca <- ggplot(pca.vectors, aes(x=X1, y=X2, color = pop)) +
  geom_point(size=3, alpha=0.9) + geom_label(label=cov) +
  scale_color_manual(values = c("#979797","black")) +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = c(0.9, 0.9),
        legend.background = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_blank(), 
        axis.line = element_line(color="black")) +
  xlab("PC1 (23.86%)") + ylab("PC2 (10.43%)") 

pca
```
