---
title: "pixy_pi"
author: "Anna Maria Calderon"
date: "2025-10-21"
output: html_document
---

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/pixy/neutral/neu_2pops_pi.txt /Users/abc6435/Desktop/KROH/data/pixy
```

# Import Data

```{r import_data, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/pixy")
pi <- read.table("neu_2pops_pi.txt", header = TRUE)
```

# Genome-Wide Pi and Ne

```{r genome_wide_pi, include=FALSE}
C <- na.omit(pi[pi$pop=="cKIWA",c("avg_pi","no_sites")])
H <- na.omit(pi[pi$pop=="hKIWA",c("avg_pi","no_sites")])


cKIWA_Ne <- mean(H$avg_pi)/(4*2e-9)
```

# Plot Data

```{r plot_data, include=FALSE}

pi$chromosome <- factor(pi$chromosome, levels = unique(pi$chromosome))
ggplot(pi, aes(x = window_pos_2, y = avg_pi, color=pop)) +
  geom_point(alpha=0.7) + 
  scale_color_manual(values=c("black","gray")) +
  facet_grid(. ~ chromosome, scales = "free_x", space = "free_x", switch="x") +
  theme_minimal() +
  theme(axis.line = element_line(color="black"),
        axis.ticks = element_blank(),
        axis.text.y = element_text(size=5, color="black"),
        axis.title.y = element_text(size=5, color="black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size=5),
        strip.text.x = element_text(angle=90, vjust = 0.5),
        strip.placement = "outside",
        #plot.background = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.spacing = unit(0.0, 'points'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(y = expression(pi))
```
