---
title: "plink"
author: "Anna Maria Calderon"
date: "2025-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/roh/plink/het_1/plink_het1_ind.txt /Users/abc6435/Desktop/KROH/data/roh

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/roh/plink/het_1/plink_het1.txt /Users/abc6435/Desktop/KROH/data/roh

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/roh/plink/het_3/plink_het3_ind.txt /Users/abc6435/Desktop/KROH/data/roh

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/roh/plink/het_3/plink_het3.txt /Users/abc6435/Desktop/KROH/data/roh
```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(reshape2)
```

# Import / Modify Data

```{r import_data, include=TRUE}
setwd("/Users/abc6435/Desktop/KROH/data/roh")
het1_roh <- read.delim("plink_het1_ind.txt", header=FALSE, sep = " ")
het1_class <- read.delim("plink_het1.txt", header=FALSE, sep = " ")
het3_roh <- read.delim("plink_het3_ind.txt", header=FALSE, sep = " ")
het3_class <- read.delim("plink_het3.txt", header=FALSE, sep = " ")
```

```{r modify_data, include=TRUE}
#Het1
colnames(het1_roh) <- c("DROP", "DROP2", "ID", 
                        "DROP3", "NROH", "SROH",
                        "AVG", "DROP4")
het1_roh <- het1_roh[-1,c(3,5:7)]
rownames(het1_roh) <- NULL
het1_roh$POP <- "NA"
het1_roh[1:7,"POP"] <- "contemporary"
het1_roh[8:13,"POP"] <- "historical"
het1_roh[,2] <- as.numeric(het1_roh[,2])
het1_roh[,3] <- as.numeric(het1_roh[,3])
het1_roh[,4] <- as.numeric(het1_roh[,4])

#Het3
colnames(het3_roh) <- c("DROP", "DROP2", "ID", 
                        "DROP3", "NROH", "SROH",
                        "AVG", "DROP4")
het3_roh <- het3_roh[-1,c(3,5:7)]
rownames(het3_roh) <- NULL
het3_roh$POP <- "NA"
het3_roh[1:7,"POP"] <- "contemporary"
het3_roh[8:13,"POP"] <- "historical"
het3_roh[,2] <- as.numeric(het3_roh[,2])
het3_roh[,3] <- as.numeric(het3_roh[,3])
het3_roh[,4] <- as.numeric(het3_roh[,4])


#Het1  Class
het1_class <- het1_class[-1,c(2,10)]
colnames(het1_class) <- c("ID", "ROH_Kb")
het1_class$ROH_Mb <- as.numeric(het1_class$ROH_Kb)/1000

het1_0.5_1MB <- subset(het1_class, (ROH_Mb >= 0.5 & ROH_Mb<1.0))
het1_0.5_1MB$Class <- "<1Mb"

het1_1_2MB <- subset(het1_class, ROH_Mb>1.0)
het1_1_2MB$Class <- "1-2Mb"

het1_class <- rbind(het1_0.5_1MB, het1_1_2MB)[,c(1,4)]

het1_class <- het1_class %>%
  group_by(ID) %>%
  summarise(
    roh_0.5_1Mb = sum(Class == "<1Mb"),
    roh_1_2Mb = sum(Class == "1-2Mb")
    ) %>% as.data.frame()

hKIWA_het1 <- c("183195312","29779","383194","383202","383205","507264","507265")
hKIWA_df_het1 <- as.data.frame(cbind(as.numeric(hKIWA_het1), as.numeric(rep(0,7)), as.numeric(rep(0,7))))
colnames(hKIWA_df_het1) <- colnames(het1_class)

het1_class <- rbind(het1_class, hKIWA_df_het1)
het1_class$pop <- "NA"
het1_class[1:7,"pop"] <- "contemporary"
het1_class[8:13,"pop"] <- "historical"
colnames(het1_class) <- c("sample", ">1Mb", "1-2Mb", "pop")
het1_class <- melt(het1_class, id.vars=c("sample", "pop"), 
                   variable.name = "class", value.name = "nroh")


#Het3  Class
het3_class <- het3_class[-1,c(2,10)]
colnames(het3_class) <- c("ID", "ROH_Kb")
het3_class$ROH_Mb <- as.numeric(het3_class$ROH_Kb)/1000

het3_0.5_1MB <- subset(het3_class, (ROH_Mb >= 0.5 & ROH_Mb<1.0))
het3_0.5_1MB$Class <- "<1Mb"

het3_1_2MB <- subset(het3_class, (ROH_Mb>1.0 & ROH_Mb<2.0))
het3_1_2MB$Class <- "1-2Mb"

het3_2_3MB <- subset(het3_class, ROH_Mb>2.0)
het3_2_3MB$Class <- "2-3Mb"

het3_class <- rbind(het3_0.5_1MB, het3_1_2MB, het3_2_3MB)[,c(1,4)]

het3_class <- het3_class %>%
  group_by(ID) %>%
  summarise(
    roh_0.5_1Mb = sum(Class == "<1Mb"),
    roh_1_2Mb = sum(Class == "1-2Mb"), 
    roh_2_3Mb = sum(Class == "2-3Mb")
    ) %>% as.data.frame()

hKIWA_het3 <- c("29779","383194","383202","383205","507264","507265")
hKIWA_df_het3 <- as.data.frame(cbind(as.numeric(hKIWA_het3), 
                                     as.numeric(rep(0,6)), 
                                     as.numeric(rep(0,6)), 
                                     as.numeric(rep(0,6))))

colnames(hKIWA_df_het3) <- colnames(het3_class)

het3_class <- rbind(het3_class, hKIWA_df_het3)
het3_class$pop <- "NA"
het3_class[1:7,"pop"] <- "contemporary"
het3_class[8:13,"pop"] <- "historical"
colnames(het3_class) <- c("sample", ">1Mb", "1-2Mb", "2-3Mb","pop")
het3_class <- melt(het3_class, id.vars=c("sample", "pop"), 
                   variable.name = "class", value.name = "nroh")

```

# Plot SROH-NROH

```{r}
#Het1
leg <- c("contemporary" = "gray","historical" = "black")
ggplot(het1_roh, aes(x=SROH/(1000), y=NROH)) + 
  geom_point(shape = 21, size = 3, 
             colour = "black", stroke = 1, aes(fill=POP)) +
  scale_fill_manual(values=alpha(leg, 1.0)) +
  xlab("SROH(Mb)") + 
  ylab("NROH") +
  scale_y_continuous(breaks = seq(0, 130, 10), limits = c(0,130)) +
  geom_abline(slope=1, intercept = 0) +
  theme(
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black"),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill=NA), 
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(0,0,0,0),
    legend.box.spacing = unit(0, "pt"))

#Het3
leg <- c("contemporary" = "gray","historical" = "black")
ggplot(het3_roh, aes(x=SROH/(1000), y=NROH)) + 
  geom_point(shape = 21, size = 3, 
             colour = "black", stroke = 1, aes(fill=POP)) +
  scale_fill_manual(values=alpha(leg, 1.0)) +
  xlab("SROH(Mb)") + 
  ylab("NROH") +
  scale_x_continuous(breaks = seq(0, 140, 20), limits = c(0,140)) +
  scale_y_continuous(breaks = seq(0, 250, 20), limits = c(0,250)) +
  geom_abline(slope=1, intercept = 0) +
  theme(
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black"),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill=NA), 
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(0,0,0,0),
    legend.box.spacing = unit(0, "pt"))
```

# Plot ROH Class

```{r plot_rohclass, include=FALSE}
leg <- c("contemporary" = "gray","historical" = "black")
ggplot(het3_class, aes(x=class, y=nroh)) + 
  geom_boxplot(aes(fill=pop)) + 
  geom_jitter(position = position_jitterdodge(jitter.width=0.2),
              pch=21, size=1, stroke=0.5, alpha=0.6, aes(fill=pop)) +
  scale_fill_manual(values=leg) +
  xlab("ROH Size Class") + 
  ylab("") +
  scale_y_continuous(breaks = seq(0, 90, 10), limits = c(0,90)) +
  theme(
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black"),
    panel.background = element_blank(), 
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.border = element_rect(color = "black", fill=NA), 
    legend.key = element_blank(),
    legend.title = element_blank(),
    legend.position = "bottom",
    legend.margin = margin(0,0,0,0),
    legend.box.spacing = unit(0, "pt"))

```
