---
title: "rxy"
author: "Anna Maria Calderon"
date: "2025-03-26"
output: html_document
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rxy/downsampled/rxy_results_downsampled.txt /Users/annamariacalderon/Desktop/KROH/data/rxy

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rxy/rxy_results.txt /Users/annamariacalderon/Desktop/KROH/data/rxy

```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
setwd("/Users/annamariacalderon//Desktop/KROH/data/rxy")
rxy <- read.table("rxy_results.txt", header = FALSE, sep = ' ')
```

# Modify Data

```{r modify_data, include=FALSE}
#intergenic_1
rxy_v1 <- subset(rxy, V5=="INTER1")
rxy_v1 <- rxy_v1[,-5]
rxy_v1$V0 <- 1
rownames(rxy_v1) <- NULL
rxy_v1$V00 <- as.numeric(rownames(rxy_v1))
rxy_v1 <- rxy_v1[,c(5,1:4,6)]
colnames(rxy_v1) <- c("RXY_1", "RXY_2", "q025", "q975", "MUT", "MUT_NUM")

#intergenic_2
rxy_v2 <- subset(rxy, V5=="INTER2")
rxy_v2 <- rxy_v2[,-5]
rxy_v2$V0 <- 1
rownames(rxy_v2) <- NULL
rxy_v2$V00 <- as.numeric(rownames(rxy_v2))
rxy_v2 <- rxy_v2[,c(5,1:4,6)]
colnames(rxy_v2) <- c("RXY_1", "RXY_2", "q025", "q975", "MUT", "MUT_NUM")
```

# Plot

```{r plot, include=FALSE}
colors = c("#fe0fac","#e7a2ff","gray","#ff9e6b","#4DD0FF","#ccff6b")
rxy_plot1 <- ggplot(rxy_v1, aes(y=MUT_NUM, fill=MUT)) +
  geom_rect(aes(xmin=RXY_1, xmax=RXY_2, 
                ymin=MUT_NUM-0.4, ymax=MUT_NUM+0.41), color="black") +
  scale_fill_manual(values = colors) +
  geom_errorbarh(aes(xmin = q025, xmax = q975, 
                     y = MUT_NUM), height = 0.2) +
  scale_x_continuous(limits=c(0,1.5), breaks=seq(0,1.5,0.2)) +
  scale_y_continuous(
    breaks = rxy_v1$MUT_NUM,
    labels = c("Deleterious","Loss of Function","Noncoding",
               "Synonymous","Nonsynonymous","Tolerated")) +
  geom_vline(xintercept = 1.0, color="black") +
  theme(
    panel.background = element_blank(),
    panel.grid.minor.x = element_line(linetype="dashed", color="black", size=0.05),
    panel.border = element_rect(color="black", fill=NA), 
    axis.title.y = element_blank(),
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black")) +
  xlab("Rxy") +
  guides(fill = "none")

rxy_plot2 <- ggplot(rxy_v2, aes(y=MUT_NUM, fill=MUT)) +
  geom_rect(aes(xmin=RXY_1, xmax=RXY_2, 
                ymin=MUT_NUM-0.4, ymax=MUT_NUM+0.41), color="black") +
  scale_fill_manual(values = colors) +
  geom_errorbarh(aes(xmin = q025, xmax = q975, 
                     y = MUT_NUM), height = 0.2) +
  scale_x_continuous(limits=c(0,1.5), breaks=seq(0,1.5,0.2)) +
  scale_y_continuous(
    breaks = rxy_v1$MUT_NUM,
    labels = c("Deleterious","Loss of Function","Noncoding",
               "Synonymous","Nonsynonymous","Tolerated")) +
  geom_vline(xintercept = 1.0, color="black") +
  theme(
    panel.background = element_blank(),
    panel.grid.minor.x = element_line(linetype="dashed", color="black", size=0.05),
    panel.border = element_rect(color="black", fill=NA), 
    axis.title.y = element_blank(),
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black")) +
  xlab("Rxy") +
  guides(fill = "none")
```

# Arrange and Save

```{r arrange_save, include=FALSE}
#rxy_plot <- ggarrange(rxy_plot1, rxy_plot2,
          #labels = c("A", "B"),
          #nrow = 1,
          #ncol=2)

ggsave("rxy.png", plot=rxy_plot1, 
       path ="/Users/annamariacalderon/Desktop/KROH/figures",
       width = 3, height = 2, units = "in", dpi = 300)
```
