---
title: "rxy"
author: "Anna Maria Calderon"
date: "2025-03-26"
output: html_document
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/slim/rxy/rxy.txt ~/Desktop/KROH/data/slim/rxy

```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
setwd("~/Desktop/KROH/data/slim/rxy")
rxy <- read.table("rxy.txt", 
                  header = FALSE, 
                  na.strings = c("nan", "NaN", "NA", "."))
rxy <- na.omit(rxy)
colnames(rxy) <- c("rxy_x", "q025", "q975", "s", "h")
rownames(rxy) <- NULL
rxy$rxy_y <- as.numeric(rownames(rxy))
rxy$h <- factor(rxy$h, levels = c("h00","h05","h10"))

```

# Modify Data

# Plot

```{r plot, include=FALSE}
ggplot(rxy, aes(y=rxy_y, fill=h, alpha=s)) +
  geom_rect(aes(xmin=1, xmax=rxy_x, 
                ymin=rxy_y-0.4, ymax=rxy_y+0.41), color="black") +
  scale_fill_manual(values = c("#FFB700","#006359","#9E005C"),
                    labels = c("h=0.0", "h=0.5", "h=1.0")) +
  scale_alpha_manual(values=c(0.4,0.7,1.0)) +
  geom_errorbarh(aes(xmin = q025, xmax = q975, 
                     y = rxy_y), height = 0.2) +
  scale_x_continuous(limits=c(0,2.0), breaks=seq(0,2.0,0.2)) +
  scale_y_continuous(breaks = rxy$rxy_y,
                     labels = c(rxy$s[1],rxy$s[2],rxy$s[3],rxy$s[4],
                                rxy$s[5], rxy$s[6])) +
  geom_vline(xintercept = 1.0, color="black") +
  theme(legend.title = element_blank(),
    panel.background = element_blank(),
    panel.grid.minor.x = element_line(linetype="dashed",
                                      color="black", linewidth=0.05),
    panel.border = element_rect(color="black", fill=NA), 
    axis.title.y = element_blank(),
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black")) +
  xlab("Rxy") +
  guides(alpha = "none")


```
