---
title: "smc++_estimate_plot"
output: html_document
date: "2025-04-17"
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/smc++/bootstrap/bootstrap_results.txt /Users/abc6435/Desktop/KROH/data/smc++

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/smc++/results_cKIWA/plot.csv /Users/abc6435/Desktop/KROH/data/smc++
```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
setwd("/Users/abc6435/Desktop/KROH/data/smc++/")

#Bootstraps
bootstrap_df <- as.data.frame(read.delim("bootstrap_results.txt", 
                           sep = '\t',
                           header = FALSE,
                           col.names = c("TimePoint", "GenAgo","Ne","rep")))

#Genome-Wide Ne Estimates
cKIWA_Ne_data <- read.csv("plot.csv")
```

# Modify Data 

```{r import_modify_data, include=FALSE}
#Average Generations Across Reps
gen <- reshape(bootstrap_df,
                   idvar="TimePoint",
                   v.names = "GenAgo",
                   timevar = "rep",
                   direction="wide")

gen <- gen[,c(-1,-2)]
avg_gen <- rowMeans(gen)

#Calculate 5th and 95th% across reps
ne <- reshape(bootstrap_df,
                     idvar="TimePoint",
                     v.names = "Ne",
                     timevar = "rep",
                     direction="wide")

ne <- ne[,c(-1,-2)]
quant_ne <- t(apply(ne, 1, quantile, probs = c(0.05, 0.95), na.rm = TRUE))

#Bind Dataset
bootstrap_quant <- as.data.frame(cbind(avg_gen, quant_ne))
bootstrap_quant$YearsAgo <- bootstrap_quant[,'avg_gen']*2
colnames(bootstrap_quant) <- c("avg_gen", "fifth", "ninety_fifth", "YearsAgo")
bootstrap_quant <- bootstrap_quant[,-1]

#Genome-Wide
colnames(cKIWA_Ne_data) <- c("Pop", "GenerationsAgo", "Ne", "plot_type", "plot_num")
cKIWA_Ne_data$YearsAgo <- cKIWA_Ne_data[,'GenerationsAgo']*2
cKIWA_Ne <- cKIWA_Ne_data[,c('YearsAgo', "Ne")]
```

# Compute Loess

```{r}
# Compute LOESS smooth for both 'fifth' and 'ninety_fifth'
loess_fifth <- loess(fifth ~ YearsAgo, data = bootstrap_quant, span = 0.25)
loess_ninety_fifth <- loess(ninety_fifth ~ YearsAgo, data = bootstrap_quant, span = 0.25)

# Create a new data frame with the smoothed values
smooth_boots_df <- data.frame(
  YearsAgo = bootstrap_quant$YearsAgo,
  fifth_smooth = predict(loess_fifth),
  ninety_fifth_smooth = predict(loess_ninety_fifth)
)

# Compute LOESS smooth for Ne
loess_Ne <- loess(Ne ~ YearsAgo, data = cKIWA_Ne, span = 0.25)

# Create a new data frame with the smoothed values
smooth_ne_df <- data.frame(
  YearsAgo = cKIWA_Ne$YearsAgo,
  Ne_smooth = predict(loess_Ne))

```

# Plot

```{r}
# Plot the data
smcpp_plot <- ggplot(smooth_boots_df, aes(x = YearsAgo/1000)) +
  geom_line(data = smooth_ne_df,
              aes(x = YearsAgo/1000, y = Ne_smooth/1000), 
              color = "red", 
              size = 1.2) + 
  geom_ribbon(aes(ymin = fifth_smooth/1000, ymax = ninety_fifth_smooth/1000),
              fill = "blue", 
              alpha = 0.3) +
  scale_x_continuous(limits = c(0,180),
                     breaks = seq(0,180, by=20),
                     expand = c(0,0)) +
  scale_y_continuous(limits = c(0,350),
                     breaks = seq(0,350, by=50)) +
  geom_point(data = bootstrap_quant, 
             aes(x = YearsAgo/1000, y = fifth/1000), 
             color = "blue", alpha = 0.5, size=0.35) +
  geom_point(data = bootstrap_quant, 
             aes(x = YearsAgo/1000, y = ninety_fifth/1000), 
             color = "blue", alpha = 0.5, size=0.35) +
  geom_point(data = cKIWA_Ne, 
             aes(x = YearsAgo/1000, y = Ne/1000), 
             color = "red", alpha = 0.5, size=0.35) +
  theme(panel.background = element_blank(),
        panel.border = element_rect(fill=NA, color="black")) +
  labs(x = "Years Ago (Kya)", 
       y = expression(italic(N[e] * 10^3)))


#Save
ggsave("smcpp_plot.png", 
       plot = smcpp_plot, 
       path = "/Users/abc6435/Desktop/KROH/figures/", 
       units = "in",
       width = 4, 
       height = 4, 
       dpi = 300)

```
