---
title: "extract_sift_annotations"
author: "Anna Maria Calderon"
date: "5/1/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r load_packages, include=FALSE}
library(stringr)
library(tibble)
library(dplyr)
library(readr)
library(tidyr)
```

# Import and Clean Data

```{r Importing_data, message=FALSE, warning=FALSE, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/rxy")
d <- read.table("SIFT_Set_Clean.txt", sep = "\t", na.strings = T)

#Reformatting V6: gsub(pattern, replacement, x) function to remove the comma and everything after the comma.
d$V6 <- gsub(',.*','', d$V6)
```

# Subset Non-coding

```{r subset_noncoding, message=FALSE, warning=FALSE, include=FALSE}
noncode1 <- subset(d, V5=="NONCODING" & (V7=="" | V7=="NA" | V7 == "NONCODING"))
noncode2 <- subset(d, (V5=="" | V5=="NA") & V7=="NONCODING")

noncoding <- rbind(noncode1, noncode2)

colnames(noncoding) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
noncoding <- noncoding[,c('CHROM', 'POS', 'MUTATION')]

#Save File 
write.table(noncoding, file="/Users/abc6435/Desktop/KROH/data/rxy/noncoding.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)
```

# Subset Synonymous

```{r subset_synonymous, message=FALSE, warning=FALSE, include=FALSE}
syn1 <- subset(d, V5=="SYNONYMOUS" & (V7=="" | V7=="NA" | V7 == "NONCODING" | V7=="SYNONYMOUS"))
syn2 <- subset(d, ((V5=="" | V5=="NA" | V5=="NONCODING") & V7=="SYNONYMOUS"))

synonymous <- rbind(syn1, syn2)

colnames(synonymous) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
synonymous <- synonymous[,c('CHROM', 'POS', 'MUTATION')]

#Save File 
write.table(synonymous, file="/Users/abc6435/Desktop/KROH/data/rxy/synonymous.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)
```

# Subset Non-synonymous

```{r subset_nonsynonymous, message=FALSE, warning=FALSE, include=FALSE}
nonsyn1 <- subset(d, V5=="NONSYNONYMOUS" & (V7=="" | V7=="NA" | V7 == "NONCODING" | V7=="SYNONYMOUS" | V7=="NONSYNONYMOUS"))
nonsyn2 <- subset(d, ((V5=="" | V5=="NA" | V5=="NONCODING" | V5=="SYNONYMOUS") & V7=="NONSYNONYMOUS"))

nonsynonymous <- rbind(nonsyn1, nonsyn2)

colnames(nonsynonymous) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
nonsynonymous <- nonsynonymous[,c('CHROM', 'POS', 'MUTATION')]

#Save File 
write.table(nonsynonymous, file="/Users/abc6435/Desktop/KROH/data/rxy/nonsynonymous.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)
```

# Subset Loss Of Function

```{r subset_lof, message=FALSE, warning=FALSE, include=FALSE}
stop_gain <- subset(d, V5=="STOP-GAIN" | V7=="STOP-GAIN")
stop_loss <- subset(d, V5=="STOP-LOSS" | V7=="STOP-LOSS")
start_lost <- subset(d, V5=="START-LOST" | V7=="START-LOST")

lof <- rbind(stop_gain, stop_loss, start_lost)

colnames(lof) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
lof <- lof[,c('CHROM', 'POS', 'MUTATION')]

#Save File 
write.table(lof, file="/Users/abc6435/Desktop/KROH/data/rxy/lossoffunction.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)

```

# Subset Tolerated

```{r subset_tol, message=FALSE, warning=FALSE, include=FALSE}
#not including lof and noncoding sites
d2 <- rbind(nonsyn1, nonsyn2, syn1, syn2)
tolerated <- subset(d2, V6=="TOLERATED" & (V8=="" | V8=="NA" | V8 == "TOLERATED"))

colnames(tolerated) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
tolerated <- tolerated[,c('CHROM', 'POS', 'MUTATION')]
tolerated$MUTATION <- "TOLERATED"

#Save File 
write.table(tolerated, file="/Users/abc6435/Desktop/KROH/data/rxy/tolerated.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)
```

# Subset Deleterious

```{r subset_tol, message=FALSE, warning=FALSE, include=FALSE}
deleterious <- subset(d2, V6=="DELETERIOUS" | V8 == "DELETERIOUS")

colnames(deleterious) <- c('CHROM', 'POS', 'REF', 'ALT', 'MUTATION')
deleterious <- deleterious[,c('CHROM', 'POS', 'MUTATION')]
deleterious$MUTATION <- "DELETERIOUS"

#Save File 
write.table(deleterious, file="/Users/abc6435/Desktop/KROH/data/rxy/deleterious.txt", row.names = FALSE, col.names = TRUE, sep = "\t", quote = FALSE)
```

# Upload to Cluster

```{bash}
scp /Users/abc6435/Desktop/KROH/data/rxy/* abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rxy
```
