---
title: "slim_s_coef"
author: "Anna Maria Calderon"
date: "2025-10-29"
output: html_document
---

# Extract Selection Coef

```{bash}
#Download to Local
work="/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/slim/rxy"
rsync abc6435@submit.hpc.psu.edu:$work/h00/h00_s.txt /Users/abc6435/Desktop/KROH/data/slim/rxy/h00
```

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

# Import Data and Modify

```{r import_data, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/slim/rxy/h00")
s <- read.table("h00_s.txt")
s <- data.frame(s[s!=0])
colnames(s) <- "value"
s$bin <- cut(s$value, breaks=c(-0.10, -0.08,-0.06,-0.04,-0.02,0.0), include.lowest=TRUE, right=TRUE)

bins <- c("[-0.1,-0.08]",
          "(-0.08,-0.06]",
          "(-0.06,-0.04]",
          "(-0.04,-0.02]",
          "(-0.02,0]")
counts <- c(nrow(s[s$bin=="[-0.1,-0.08]",]),
            nrow(s[s$bin=="(-0.08,-0.06]",]),
            nrow(s[s$bin=="(-0.06,-0.04]",]),
            nrow(s[s$bin=="(-0.04,-0.02]",]),
            nrow(s[s$bin=="(-0.02,0]",]))
s_sum <- as.data.frame(cbind(bins,as.numeric(counts)))
colnames(s_sum) <- c("bins","count")
s_sum$bins <- factor(s_sum$bins, levels = s_sum$bins)
s_sum$count <- as.numeric(s_sum$count)
```

# Plot

```{r plot, include=FALSE}
h_00 <- "#F099C0"
h_02 <- "#EA71A7"
h_05 <- "#DE2176"
h_10 <- "#9E1854"

ylim_max <- round(max(s_sum$count) + 100, -2)
s_dist <- ggplot(s_sum, aes(x = bins, y=counts)) +
  geom_bar(stat="identity", fill = h_00, color = "black") +
  scale_y_continuous(expand=c(0,0), limits=c(0,ylim_max)) +
   theme(
    panel.background = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.border = element_rect(color="black", fill=NA), 
    axis.title.y = element_text(size=8, color="black"),
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black")) +
  xlab("s") +
  ggtitle("h = 0.0")

ggsave("/Users/abc6435/Desktop/fit_dist_h00.png", 
       plot=s_dist, 
       dpi=300, 
       units = "cm",
       width = 10,
       height = 10)
```
