---
title: "slim_s_coef"
author: "Anna Maria Calderon"
date: "2025-10-29"
output: html_document
---

# Extract S

```{bash}
work="/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/slim/rxy"
h_coef="h00 h05 h10"
for h in $h_coef; do
    rsync abc6435@submit.hpc.psu.edu:$work/$h/$h_s.txt /Users/abc6435/Desktop/KROH/data/slim/rxy/$h
done
```

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
```

# Import Data and Modify

```{r import_data, include=FALSE}
setwd("/Users/abc6435/Desktop/KROH/data/slim/rxy")

#h=0
s_00 <- read.table("h00/h00_s.txt")
s_00 <- data.frame(s_00[s_00!=0])
colnames(s_00) <- "value"

#h=0.5
s_05 <- read.table("h05/h05_s.txt")
s_05 <- data.frame(s_05[s_05!=0])
colnames(s_05) <- "value"

#h=1.0
s_10 <- read.table("h10/h10_s.txt")
s_10 <- data.frame(s_10[s_10!=0])
colnames(s_10) <- "value"
```

# Plot

```{r plot, include=FALSE}
#h=0.0
h00 <- hist(s_00$value,
            breaks = c(-0.25, -0.10, -0.05, 0.00), plot = FALSE)
plot(h00,
     freq = TRUE,
     main = "h=0.0",
     xlab = "s",
     ylab = "count",
     col = "#FFB700",
     ylim = c(0, max(h00$counts) * 1.2))
text(x = h00$mids,
     y = h00$counts,
     labels = h00$counts,
     pos = 3,
     cex = 0.8)

#h=0.5
h05 <- hist(s_05$value,
            breaks = c(-0.25, -0.10, -0.05, 0.00), plot = FALSE)
plot(h05,
     freq = TRUE,
     main = "h=0.5",
     xlab = "s",
     ylab = "count",
     col = "#006359",
     ylim = c(0, max(h05$counts) * 1.2))
text(x = h05$mids,
     y = h05$counts,
     labels = h05$counts,
     pos = 3,
     cex = 0.8)

#h=1.0
h10 <- hist(s_10$value,
            breaks = c(-0.25, -0.10, -0.05, 0.00), plot = FALSE)
plot(h10,
     freq = TRUE,
     main = "h=1.0",
     xlab = "s",
     ylab = "count",
     col = "#9E005C",
     ylim = c(0, max(h10$counts) * 1.2))
text(x = h10$mids,
     y = h10$counts,
     labels = h10$counts,
     pos = 3,
     cex = 0.8)


```
