---
title: "gone_snps_dist"
author: "Anna Maria Calderon"
date: "2025-02-20"
output: html_document
---

## Setup

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(knitr)
```

## Download Data

```{bash}
#Set Variables
gone_folder="/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/gone"

#Rsync Data
for i in $(seq 2 5); do
  rsync abc6435@submit.hpc.psu.edu:$gone_folder/gone_${i}M/gone.map /Users/abc6435/Desktop/KROH/data/gone/gone_${i}.map;
done

for i in $(seq 1 10); do
  rsync abc6435@submit.hpc.psu.edu:$gone_folder/gone_${i}00K/gone_rep${i}.map /Users/abc6435/Desktop/KROH/data/gone;
done
```

## Import Data

```{r import_data; include=FALSE}

setwd("/Users/abc6435/Desktop/KROH/data/gone")
map_2M <- read.table("gone_2.map", header = TRUE)
map_3M <- read.table("gone_3.map", header = TRUE)
map_4M <- read.table("gone_4.map", header = TRUE)
map_5M <- read.table("gone_5.map", header = TRUE)
map_100K <- read.table("gone_rep1.map", header = TRUE)
map_200K <- read.table("gone_rep2.map", header = TRUE)
map_300K <- read.table("gone_rep3.map", header = TRUE)
map_400K <- read.table("gone_rep4.map", header = TRUE)
map_500K <- read.table("gone_rep5.map", header = TRUE)
map_600K <- read.table("gone_rep6.map", header = TRUE)
map_700K <- read.table("gone_rep7.map", header = TRUE)
map_800K <- read.table("gone_rep8.map", header = TRUE)
map_900K <- read.table("gone_rep9.map", header = TRUE)
map_1000K <- read.table("gone_rep10.map", header = TRUE)
```

## Plot Data

```{r plot}

ggplot(map_2M, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#00ff55", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_3M, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#913bb9", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_4M, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#4ebbff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_5M, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#f722ff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_100K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#ff7777", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_200K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#ffb877", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_300K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#ffe21c", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_400K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#d5ff1c", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_500K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#62ff1c", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_600K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#1cffbe", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_700K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#1ccdff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_800K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#1c91ff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_900K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#561cff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))

ggplot(map_1000K, aes(x=X1)) + 
  geom_histogram(binwidth = 1, fill="#c31cff", color="black") +
  scale_x_continuous(breaks = seq(1,30,1)) +
  xlab("Chromosome") +
  ylab("Count") +
  ggtitle("SNPs Per Chromosome") +
  theme(panel.background = element_rect(fill = NA, color="black"))
```
