---
title: "divstats_pi"
author: "Anna Maria Calderon"
date: "2025-10-21"
output: html_document
---

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(reshape2)
```

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/group/zps5164/default/abc6435/KROH/data/divstats/divstats_sites.txt /Users/abc6435/Desktop/KROH/data/divstats
```

# Import Data

```{r import_data, include=FALSE}
setwd("~/Desktop/KROH/data/divstats")
df <- read.table("divstats_sites.txt", header = TRUE)
df <- na.omit(df)
```

# Modify Data

```{r modify_data, include=FALSE}
#Subset by pop
pi_cKIWA <- subset(df, POP=="cKIWA")
pi_hKIWA <- subset(df, POP=="hKIWA")

# Merge on common sites
pi_ij <- inner_join(pi_cKIWA[,c(1,2,3)], pi_hKIWA[,c(1,2,3)], by = c("CHR", "POS"))
colnames(pi_ij) <- c("CHR", "POS", "cKIWA", "hKIWA")

#Melt 
pi_m <- melt(pi_ij, id.vars=c("CHR","POS"), value.name="PI", variable.name="POP")
```

# Plot Data

```{r plot_data, include=FALSE}

ggplot(pi_m, aes(x = PI, color=POP)) +
  geom_density(alpha = 0.6) +
  facet_wrap(~CHR, scales = "free_y") +
  theme_bw() +
  labs(x = "Per-site π", y = "Density")



pi_m$CHR <- factor(pi_m$CHR, levels = unique(pi_m$CHR))
ggplot(pi_m, aes(x = POS, y = PI, color=POP)) +
  geom_line(alpha=0.7) + 
  scale_color_manual(values=c("gray","black")) +
  facet_grid(. ~ CHR, scales = "free_x", space = "free_x", switch="x") +
  theme_minimal() +
  theme(axis.line = element_line(color="black"),
        axis.ticks = element_blank(),
        axis.text.y = element_text(size=10, color="black"),
        axis.title.y = element_text(size=10, color="black"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text = element_text(size=8),
        strip.text.x = element_text(angle=90, vjust = 0.5),
        strip.placement = "outside",
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.border = element_blank(),
        panel.spacing = unit(0.0, 'points'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank()) +
  labs(y = expression(pi))
```
