---
title: "rxy"
author: "Anna Maria Calderon"
date: "2025-03-26"
output: html_document
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rab/results.txt /Users/abc6435/Desktop/KROH/data/rab
```

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
library(reshape2)
setwd("/Users/abc6435/Desktop/KROH/data/rab")
df <- read.table("results.txt", header = TRUE)
```

# Modify Data

```{r modify_data, include=FALSE}
rab <- rbind(
  subset(df, df$MUT=="lossoffunction"),
  subset(df, df$MUT=="deleterious"),
  subset(df, df$MUT=="nonsynonymous"),
  subset(df, df$MUT=="tolerated"),
  subset(df, df$MUT=="synonymous"),
  subset(df, df$MUT=="noncoding"))

rownames(rab) <- NULL
rab$NUM <- c(1,2,4,5,7,8,10,11,13,14,16,17)
```

# Plot

```{r plot, include=FALSE}
colors = c(
  "lossoffunction"="#FF12B4",
  "deleterious"="#C870E0",
  "nonsynonymous"="#7083E0",
  "tolerated"="#70E0CA",
  "synonymous"="#C1E070",
  "noncoding"="#FFD400"
)

rab_plot <- ggplot(rab, aes(y=NUM, fill=MUT, alpha=NEUTRAL)) +
  geom_rect(aes(xmin=1, xmax=AVG, ymin=NUM-0.4, ymax=NUM+0.4),
            color="black") +
  geom_point(aes(x=RAB, y=NUM),size = 1) +
  scale_alpha_manual(values=c(1,0.5), name=NULL) +
  scale_fill_manual(values = colors, guide="none") +
  geom_errorbarh(aes(xmin = Q25, xmax = Q97, y = NUM), height = 0.2) +
  scale_x_continuous(limits=c(0,1.5), breaks=seq(0,1.5,0.2)) +
  scale_y_continuous(
    breaks = c(1.5,4.5,7.5,10.5,13.5,16.5),
    labels = unique(rab$MUT)) +
  geom_vline(xintercept = 1.0, color="black") +
  theme(
    panel.background = element_blank(),
    panel.grid.minor.x = element_line(linetype="dashed", color="black", linewidth=.05),
    panel.border = element_rect(color="black", fill=NA), 
    axis.title.y = element_blank(),
    axis.text.x = element_text(size=8, color="black"),
    axis.text.y = element_text(size=8, color="black"),
    legend.position = "bottom") +
  xlab("RAB") 
```

# Arrange and Save

```{r arrange_save, include=FALSE}
ggsave("rab.png", plot=rab_plot, 
       path ="~/Desktop/KROH/figures",
       width = 4, height = 4.5, units = "in", dpi = 300)
```
