---
title: "rxy"
author: "Anna Maria Calderon"
date: "2025-03-26"
output: html_document
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/group/zps5164/default/abc6435/KROH/data/slim/vcf/results/results.txt ~/Desktop/KROH/data/slim/results

```

# Import Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
library(reshape2)
library(ggpattern)
library(tidyverse)
setwd("~/Desktop/KROH/data/slim/results")

#rab
df <- read.table("results.txt",
                 sep="\t",
                 header = FALSE, 
                 col.names = c("mut","n_sites","rab", "ahom","ahet","bhom","bhet","h","rep"))
rab <- na.omit(df)
rab$mut <- factor(rab$mut, levels = c("neutral", "mild", "moderate", "strong"))

#zygosity proportions
rab$p_ahom <- rab$ahom/(rab$ahom+rab$ahet)
rab$p_ahet <- rab$ahet/(rab$ahom+rab$ahet)
rab$p_bhom <- rab$bhom/(rab$bhom+rab$bhet)
rab$p_bhet <- rab$bhet/(rab$bhom+rab$bhet)
zygp <- rab[,c("mut", "h", "p_ahom","p_ahet", "p_bhom","p_bhet")]
zygp_m <- melt(zygp, id=c("mut", "h"), variable.name = "zygosity", value.name = "proportion")
zygp_sum <- zygp_m %>%
  group_by(mut, zygosity, h) %>%
  summarise(mean_prop = mean(proportion, na.rm=TRUE),
            sd = sd(proportion, na.rm = TRUE),
            n = sum(!is.na(proportion)), 
            se = sd/sqrt(n))

zygp_sum$pop <- zygp_sum$zygosity
zygp_sum$pop <- str_replace_all(zygp_sum$pop, "p_a[a-z]*", "A")
zygp_sum$pop <- str_replace_all(zygp_sum$pop, "p_b[a-z]*", "B")
zygp_sum$zygosity <- str_replace_all(zygp_sum$zygosity, "p_[ab]","")
zygp_sum$mut <- factor(zygp_sum$mut, levels = c("strong", "moderate", "mild", "neutral"))
```

# Plot RAB

```{r rab_plot, include=FALSE}
colors1 = c(
  "strong"="#FF4917",
  "moderate"="#FFD82B",
  "mild"="#00BF98",
  "neutral"="#82FFD5",
  "intergenic"="#82E8FF")

colors2 = c(
  "strong"="#FF4917",
  "moderate"="#FFD82B",
  "mild"="#00BF98",
  "neutral"="#82FFD5")

rab_plot <- 
  ggplot(rab, aes(x=log(rab), y=mut, fill=mut)) +
  geom_vline(xintercept = 0, color="black") +
  geom_boxplot(width=0.7, color="black", alpha=1.0, outlier.shape = NA) +
  geom_jitter(shape = 16, height = 0.05, size=0.7, alpha=0.3) +
  scale_x_continuous(limits = c(-2,2), breaks=seq(-2,2,0.5)) +
  scale_fill_manual(values = colors2) +
  facet_wrap(~h, ncol=3, scales="free_x") +
  xlab(expression(ln(RAB))) +
  theme(panel.grid.minor.x = 
          element_line(linetype="dashed", color="black", linewidth=.05),
    panel.background = element_blank(),
    panel.border = element_rect(fill=NA, color="black"),
    legend.position="none",
    strip.text = element_text(color="white"),
    strip.background = element_rect(fill="black", color=NA),
    axis.text = element_text(color="black", size=8),
    axis.title.y = element_blank())
rab_plot
```

# Plot Zygosity

```{r zygosity_plot, include=FALSE}
pd <- position_dodge(width = 0.9)
zyg_plot <- ggplot(zygp_sum 
                   %>% filter(zygosity=="hom", mut %in% c("strong", "moderate")),
       aes(x=1, y=mean_prop, fill=mut, shape=pop)) +
  geom_point(position=pd, size = 4, color = "black", stroke = 1) +
  geom_errorbar(aes(ymin = mean_prop-se, ymax = mean_prop+se), 
                position=pd, width = 0.2) +
  scale_shape_manual(values=c(22, 23), 
                     labels = c(A="pre-bottleneck", B="post-bottleneck")) +
  scale_fill_manual(values = colors2) +
  facet_grid(~h, scales = "free_y") +
  scale_x_discrete(expand = c(0.1,0.1)) +
  scale_y_continuous(expand = c(0.03,0)) +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(fill=NA, color="black"),
    strip.text = element_text(color="white"),
    strip.background = element_rect(fill="black", color=NA),
    axis.ticks.x = element_blank(),
    axis.text.y = element_text(size=8, color="black"),
    axis.text = element_text(color="black", size=8),
    axis.title.x = element_blank()) +
  guides(fill="none") +
  ylab("Mean Proportion")
```

# Arrange and Save

```{r}
sim_plots <- 
  ggarrange(rab_plot, zyg_plot, nrow=2, labels = c("A","B"))

ggsave(filename = "rab_sims_plot.png",
       plot = sim_plots,
       width = 7,
       height = 6,
       units = "in",
       dpi = 300,
       path = "~/Desktop/KROH/figures")
```
