---
title: "ROHan"
output: html_document
date: "2025-10-31"
---

# Download

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/percent_ROH.txt ~/Desktop/KROH/data/rohan

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/gw_theta_inc_ROH.txt ~/Desktop/KROH/data/rohan

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/gw_theta_outside_ROH.txt ~/Desktop/KROH/data/rohan

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/nroh_sroh.txt ~/Desktop/KROH/data/rohan

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/het.txt ~/Desktop/KROH/data/rohan 

rsync abc6435@submit.hpc.psu.edu:/storage/home/abc6435/SzpiechLab/abc6435/KROH/data/rohan/results/rohan_cov.txt ~/Desktop/KROH/data/rohan 
```

# Set Up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(ggpubr)
```

# Import Data and Modify

```{r import_datq, include=FALSE}
setwd("~/Desktop/KROH/data/rohan")

#ROHan Coverage
cov <- read.table("rohan_cov.txt", header=FALSE)
colnames(cov) <- c("sample", "cov")
cov$cov <- round(cov$cov,2)
cov$cov <- paste0(cov$cov, "x")

#Segments in ROH (%)
roh <- read.table("percent_ROH.txt", header=TRUE)
colnames(roh) <- c("sample", "fROH", "CI")
roh$sample <- as.character(roh$sample)
roh$pop <- c(rep("ckIWA",7), rep("hKIWA",6))
roh$CI <- gsub("[()]", "", roh$CI)
roh <- separate(data=roh, col="CI", into = c("min_CI","max_CI"), sep = ",")
roh$min_CI <- as.numeric(roh$min_CI)
roh$max_CI <- as.numeric(roh$max_CI)


# Genome-wide theta outside ROH
theta_o_roh <- read.table("gw_theta_outside_ROH.txt", header=TRUE)

# Genome-wide theta including ROH
theta_inc_roh <- read.table("gw_theta_inc_ROH.txt", header=TRUE)
colnames(theta_inc_roh) <- c("sample","mid","min","max")

#Merge Data
tmp1 <- merge(cov,roh,by="sample")
tmp2 <- merge(theta_o_roh, theta_inc_roh, by="sample")
roh_theta <- merge(tmp1, tmp2, by="sample")
roh_theta$sample <- factor(roh_theta$sample,
                     levels = c("183195332","183195312","183194841",
                                "183195321","183194861","183195304",
                                "183195326","507264","29779", 
                                "383194", "383202","383205","507265"))


#nroh_sroh
nroh_sroh <- read.csv("nroh_sroh.txt", header=TRUE, fill = TRUE)
nroh_sroh[is.na(nroh_sroh)] <- 0
nroh_sroh$pop <- c(rep("ckIWA",21), rep("hKIWA",18))
nroh_sroh$hmm_posterior_decoding <- factor(nroh_sroh$hmm_posterior_decoding,
                                           levels = c("min","mid","max"))

#Heterozygosity
h <- read.table("het.txt", header=TRUE)
```

# Plot ROH Theta

```{r plot_roh_theta, include=FALSE}
roh_theta_plot <- 
  ggplot(roh_theta, aes(x=sample, y=fROH, fill=pop)) +
  geom_bar(stat="identity") +
  geom_errorbar(aes(ymin=min_CI, ymax=max_CI),
                color="black",
                width=0.1) +
  geom_text(aes(label = cov), y=-1, size=2) +
  geom_point(aes(y = thetamid * 5000), 
             color = "#0099FF", 
             size = 2,
             alpha=1.0,
             show.legend = FALSE) +
  geom_point(aes(y = mid * 5000), 
             color = "#FF6600", 
             size = 2,
             alpha=0.8,
             show.legend = FALSE) +
  geom_errorbar(aes(y=thetamid*5000, ymin=thetamin*5000, ymax=thetamax*5000),
                color = "#0099FF",
                width = 0.3,
                alpha=1.0) +
  geom_errorbar(aes(y=mid*5000, ymin=min*5000, ymax=max*5000),
                color = "#FF6600",
                width = 0.3,
                alpha=0.8) +
  scale_fill_manual(values=c("gray","black")) +
  scale_y_continuous(name="ROH (%)", expand=c(0,2), limits=c(0,30),
                     sec.axis=sec_axis(~./5000,name=expression("Genomewide "*theta))) +
  labs(x = NULL) +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", fill = NA),
    legend.background = element_blank(),
    legend.title = element_blank(),
    legend.position = c(0.9,0.90),
    axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
    axis.text = element_text(color="black", size=8),
    text = element_text(size = 8))
```

# Plot NROH SROH

```{r plot_nroh_sroh, include=FALSE}
nroh_sroh_plot <- 
  ggplot(nroh_sroh, aes(x = sroh/1e6, y = nroh, color = pop)) +
  geom_point(size = 1, alpha=0.5) +
  scale_color_manual(values = c("gray", "black")) +
  facet_wrap(~hmm_posterior_decoding, ncol = 3) +
  xlab("SROH (Mb)") +
  ylab("NROH") +
  theme(
    panel.background = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_rect(color = "black", fill = NA),
    legend.background = element_blank(),
    legend.title = element_blank(),
    legend.position = "none", 
    strip.text = element_text(color="white"),
    strip.background = element_rect(fill="black", color=NA),
    axis.text = element_text(color="black", size=8),
    text = element_text(size = 8))
```

# Plot Het

```{r plot_heterozygosity, include=FALSE}
h$chrom <- factor(h$chrom, levels = unique(h$chrom))

h_plot <- 
  ggplot(h, aes(x = end, y = h, color=pop)) +
  geom_line() + 
  scale_y_continuous(expand = c(0,0)) +
  scale_color_manual(values=c("gray","black")) +
  facet_grid(. ~ chrom, scales = "free_x", space = "free_x", switch="x") +
  ylab("Heterozygosity") +
  theme(axis.line = element_line(color="black"),
        axis.ticks = element_blank(),
        #axis.text.y = element_text(size=8, color="blue"),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        strip.text.x = element_text(angle=90, vjust = 0.5, size=8, color="black"),
        strip.placement = "outside",
        strip.background = element_blank(),
        panel.background = element_blank(), 
        panel.border = element_blank(),
        panel.spacing = unit(0.0, 'points'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.key = element_rect(fill = "white", color = NA),
        axis.text = element_text(color="black", size=8),
        text = element_text(size = 8)) 
```

# Arrange and Save

```{r save, include=FALSE}

rohan_plots <- ggarrange(roh_theta_plot,
          nroh_sroh_plot,
          h_plot,
          ncol=1,
          nrow=3,
          labels = c("A","B","C"),
          common.legend = TRUE)


ggsave(filename = "rohan.png",
       plot = rohan_plots, 
       width = 4.5,
       height = 6.5,
       units = "in",
       dpi = 300,
       path = "~/Desktop/KROH/figures/")


```
