---
title: "rxy"
author: "Anna Maria Calderon"
date: "2025-03-26"
output: html_document
---

# Download Data

```{bash}
rsync abc6435@submit.hpc.psu.edu:/storage/group/zps5164/default/abc6435/KROH/data/slim/rxy/results/rxy.txt ~/Desktop/KROH/data/slim/rxy

```

# Import Data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(tidyr)
library(dplyr)
setwd("~/Desktop/KROH/data/slim/rxy")
rxy <- read.table("rxy.txt", 
                  header = FALSE, 
                  na.strings = c("nan", "NaN", "NA", "."))
rxy <- na.omit(rxy)
colnames(rxy) <- c("rxy", "q025", "q975", "s", "h","rep")
rownames(rxy) <- NULL
rxy$rxy_y <- as.numeric(rownames(rxy))
rxy$h <- factor(rxy$h, levels = c("h00","h05","h10"))
```

# Plot

```{r plot, include=FALSE}
P1=c("#1AABFF","#FFE01A","#FF1A39")
P2=c("#8FD3FF","#FFF48F","#FF8F9A")

rxy_slim <- 
  ggplot(rxy[rxy$rxy<2,], aes(x=rxy, y=s, fill=h)) +
  geom_violin(alpha=0.5, color="black", width=1.0) +
  geom_boxplot(width=0.05, color="black", outlier.shape = NA) +
  geom_jitter(shape = 16, height = 0.05, size=0.3, alpha=0.3) +
  scale_fill_manual(values = P1) +
  geom_vline(xintercept = 1.0,
             color="black",
             linetype="dashed",
             linewidth=0.15) +
  facet_wrap(~h, ncol=3, scales="free_x") +
  xlab("RAB") +
  theme(
    panel.background = element_blank(),
    panel.border = element_rect(fill=NA, color="black"),
    legend.position="none",
    strip.text = element_text(color="white"),
    strip.background = element_rect(fill="black", color=NA),
    axis.text = element_text(color="black")
  )
```

# Save

```{r save, include=FALSE}
ggsave(filename = "rab_slim_plot.png",
       plot = rxy_slim, 
       width = 6,
       height = 6,
       units = "in",
       dpi = 300,
       path = "~/Desktop/KROH/figures")
```
